### ISSUE TITLE
Runtime error with vhtml on 1.5.5

### ISSUE THREAD

**Issue by aral** [dy/xhtm#10]
```js
import htm from 'xhtm'
import vhtml from 'vhtml'

const html = htm.bind(vhtml)

let applicationIndex = 1

html `
<form method='POST' action='/settings/setup/applications/edit/${applicationIndex}'>
  <button id='add' name='add' type='submit'>Update</button>
</form>
`
```

Error:

```
TypeError: value.join is not a function
    at Array.isArray.value.toString (file:///var/home/aral/Projects/other/xhtm/htm.js:66:47)
    at String (<anonymous>)
    at esc (/var/home/aral/Projects/other/xhtm/node_modules/vhtml/dist/vhtml.js:10:9)
    at h (/var/home/aral/Projects/other/xhtm/node_modules/vhtml/dist/vhtml.js:40:83)
    at up (file:///var/home/aral/Projects/other/xhtm/htm.js:25:18)
    at file:///var/home/aral/Projects/other/xhtm/htm.js:72:9
    at String.replace (<anonymous>)
    at Function.htm (file:///var/home/aral/Projects/other/xhtm/htm.js:37:6)
```

The issue appears to surface if the tag contains children (e.g., remove the `button` from the `form` in the example above and the error goes away.

**Comment by dy** [comment]
Thanks for the report! Fixed.

**Comment by aral** [comment]
@dy Thank you so much, Dmitry :) Everything seems to be working in Kitten now. Going to do some further testing tomorrow but it looks like Kitten is moving to xhtm :)

:smile_cat: :two_hearts:
