### ISSUE TITLE
xhtm 1.5.7 aggresively pruning spaces between tags (xhtml + vhtml)

### ISSUE THREAD

**Issue by aral** [dy/xhtm#13]
Some HTML tags should maintain spaces between them (e.g., `<span>`s)

When used with vhtml, xhtm 1.5.7 removes those spaces entirely.

Failing test:

```js
t('#13: whitespace handling should match HTML specification', t => {
	const html = htm.bind(vhtml)

	const result = 
	t.equal(
		html`<p>These <span>words</span> <span>should</span>      <strong>be</strong> separated with just one space. <span>But</span><span>These</span><span>Should</span><span>Not</span>.</p>`,
		'<p>These <span>words</span> <span>should</span> <strong>be</strong> separated with just one space. <span>But</span><span>These</span><span>Should</span><span>Not</span>.</p>'
	)
})
```

Result:

```
►#13: whitespace handling should match HTML specification
× 144 — should equal
actual: "<p>These <span>words</span><span>should</span><strong>be</strong> separated with just one space. <span>But</span><span>These</span><span>Should</span><span>Not</span>.</p>"
expected: "<p>These <span>words</span> <span>should</span> <strong>be</strong> separated with just one space. <span>But</span><span>These</span><span>Should</span><span>Not</span>.</p>"
Error
    at Object.log (file:///var/home/aral/Projects/other/xhtm/node_modules/tst/index.js:89:29)
    at Object.equal (file:///var/home/aral/Projects/other/xhtm/node_modules/tst/assert.js:26:8)
    at Object.fn (file:///var/home/aral/Projects/other/xhtm/test/index.js:145:4)
    at file:///var/home/aral/Projects/other/xhtm/node_modules/tst/index.js:111:29
    at async file:///var/home/aral/Projects/other/xhtm/node_modules/tst/index.js:136:3

```

**Comment by dy** [comment]
Is that not the case for htm? 
It seems spec tends to collapse multiple spaces into a single one, isn't it?

https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

**Comment by aral** [comment]
@dy I only just noticed the issue in the latest xhtm (htm + vhtml keep at least one space).

It seems xhtm is collapsing single and multiple spaces into no spaces.

**Comment by dy** [comment]
Ok v1.5.7 has better spacing handling, please check, it should be htm-complacent.
Not html-complacent though, since html has different spacing rules for block/inline elements, not going to fully implement it.

**Comment by aral** [comment]
@dy Thanks as always, Dmitry. Going to have a play with it now :)

**Comment by aral** [comment]
@dy That seems to have broken something in one of my more complex examples. I’m trying to create a simple reproduction. It seems to be related to newlines being in tags (e.g., when you write attributes out on different lines) but I can’t reproduce it outside of Kitten yet. Will open a new issue when I can.

The code I’m seeing with 1.5.8 (which wasn’t an issue in previous versions), looks something like:

```
<p>Status: <spanid='status'x-data=',{ status:="" "initialising…"="" },'@htmx:ws-connecting.window=",status = &quot;Connecting…&quot;," @htmx:ws-open.window=",status = &quot;Online&quot;," @htmx:ws-close.window=",status = &quot;Offline&quot;," x-text="status" :class=",
        status === &quot;Online&quot; ? &quot;online&quot; : status === &quot;Offline&quot; ? &quot;offline&quot; : &quot;&quot;
      ,">Initialising…</spanid='status'x-data=',{></p>
```

For the following code in Kitten:

```js
<p>Status: <spanid='status'x-data='{ status:="" "initialising…"="" }'@htmx:ws-connecting.window="status = &quot;connecting…&quot;" @htmx:ws-open.window="status = &quot;online&quot;" @htmx:ws-close.window="status = &quot;offline&quot;" x-text="status" :class="
        status === &quot;online&quot; ? &quot;online&quot; : status === &quot;offline&quot; ? &quot;offline&quot; : &quot;&quot;
      ">Initialising…</spanid='status'x-data='{></p>
```

Whereas previously, it was:

```js
<p>Status: <span id="status" x-data="{ status: &quot;Initialising…&quot; }" @htmx:ws-connecting.window="status = &quot;Connecting…&quot;" @htmx:ws-open.window="status = &quot;Online&quot;" @htmx:ws-close.window="status = &quot;Offline&quot;" x-text="status" :class="
        status === &quot;Online&quot; ? &quot;online&quot; : status === &quot;Offline&quot; ? &quot;offline&quot; : &quot;&quot;
      " class="online">Online</span></p>
```

(I don’t expect you to be able to debug from that. Just documenting it.)

**Comment by dy** [comment]
Ok, 1.5.9 should fix it

**Comment by dy** [comment]
1.5.10 should too, but it's also faster
